SELECT * FROM mydb.players;

-- DELETE ALL IN TABLE
-- INSERT GRADES DATA

INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('1', 'Niño 1 ', '8', '2', 'A_niño1', 'A2_niño1', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('2', 'Niño 2', '8', '2', 'A_niño2', 'A2_niño2', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('3', 'Niño 3', '9', '3', 'A_niño3', 'A2_niño3', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('4', 'Niño 4', '9', '3', 'A_niño4', 'A2_niño4', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('5', 'Niño 5', '10', '4', 'A_niño5', 'A2_niño5', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('6', 'Niño 6', '10', '4', 'A_niño6', 'A2_niño6', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('7', 'Niño 7', '11', '5', 'A_niño7', 'A2_niño7', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('8', 'Niño 8', '11', '5', 'A_niño8', 'A2_niño8', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('9', 'Niño 9', '12', '6', 'A_niño9', 'A2_niño9', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('10', 'Niño 10', '12', '5', 'A_niño10', 'A2_niño10', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('11', 'Niño 11', '13', '6', 'A_niño11', 'A2_niño11', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO `mydb`.`players` (`idplayer`, `name`, `age`, `idgrade`, `lastname1`, `lastname2`, `enable`, `idCard`, `favoriteTopic`, `favoriteSubject`, `favoriteHobbie`, `otherInfo`) VALUES ('12', 'Niño 12', '13', '5', 'A_niño12', 'A2_niño12', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
